image: docker:git

stages:
  - build

before_script:
  - docker login --username=$DOCKER_AUTH_USERNAME --password=$DOCKER_AUTH_PASSWORD

#-------------------------------------------------------------------------------

php-ci:7.0:
  stage: build
  services:
    - docker:dind
  script:
    - cd php-ci
    - docker build -t chstudio/php-ci:7.0 .
    - docker push chstudio/php-ci:7.0
    - export PHP_VERSION=`docker run chstudio/php-ci:7.0 php -v | sed -n 1p | cut -d ' ' -f 2`
    - docker tag chstudio/php-ci:7.0 chstudio/php-ci:$PHP_VERSION
    - docker push chstudio/php-ci:$PHP_VERSION
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/chstudio/docker-images:php-ci_7.0
    - docker push registry.gitlab.com/chstudio/docker-images:php-ci_$PHP_VERSION
  only:
    - master

php-ci:7.1:
  stage: build
  services:
    - docker:dind
  script:
    - cd php-ci
    - sed s/php:7.0-alpine/php:7.1-alpine/ Dockerfile > Dockerfile71
    - docker build -t chstudio/php-ci:7.1 --file=Dockerfile71 .
    - docker push chstudio/php-ci:7.1
    - export PHP_VERSION=`docker run chstudio/php-ci:7.1 php -v | sed -n 1p | cut -d ' ' -f 2`
    - docker tag chstudio/php-ci:7.1 chstudio/php-ci:$PHP_VERSION
    - docker push chstudio/php-ci:$PHP_VERSION
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/chstudio/docker-images:php-ci_7.1
    - docker push registry.gitlab.com/chstudio/docker-images:php-ci_$PHP_VERSION
  only:
    - master

php-ci:latest:
  stage: build
  services:
    - docker:dind
  script:
    - cd php-ci
    - sed s/php:7.0-alpine/php:alpine/ Dockerfile > DockerfileLatest
    - docker build -t chstudio/php-ci:latest --file=DockerfileLatest .
    - docker push chstudio/php-ci:latest
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/chstudio/docker-images:php-ci_latest
  only:
    - master

#-------------------------------------------------------------------------------

php-ci.mysql:7.0:
  stage: build
  services:
    - docker:dind
  script:
    - cd php-ci.mysql
    - docker build -t chstudio/php-ci.mysql:7.0 .
    - docker push chstudio/php-ci.mysql:7.0
    - export PHP_VERSION=`docker run chstudio/php-ci.mysql:7.0 php -v | sed -n 1p | cut -d ' ' -f 2`
    - docker tag chstudio/php-ci.mysql:7.0 chstudio/php-ci.mysql:$PHP_VERSION
    - docker push chstudio/php-ci.mysql:$PHP_VERSION
  only:
    - master

php-ci.mysql:7.1:
  stage: build
  services:
    - docker:dind
  script:
    - cd php-ci.mysql
    - sed s/php-ci:7.0/php-ci:7.1/ Dockerfile > Dockerfile71
    - docker build -t chstudio/php-ci.mysql:7.1 --file=Dockerfile71 .
    - docker push chstudio/php-ci.mysql:7.1
    - export PHP_VERSION=`docker run chstudio/php-ci.mysql:7.1 php -v | sed -n 1p | cut -d ' ' -f 2`
    - docker tag chstudio/php-ci.mysql:7.1 chstudio/php-ci.mysql:$PHP_VERSION
    - docker push chstudio/php-ci.mysql:$PHP_VERSION
  only:
    - master

php-ci.mysql:latest:
  stage: build
  services:
    - docker:dind
  script:
    - cd php-ci.mysql
    - sed s/php-ci:7.0/php-ci:latest/ Dockerfile > DockerfileLatest
    - docker build -t chstudio/php-ci.mysql:latest --file=DockerfileLatest .
    - docker push chstudio/php-ci.mysql:latest
  only:
    - master
